import Head from "next/head";
import client from "../apollo-client";
import { GET_HOME_PAGE } from "../graphQL/graphql";
import Layout from "../components/layout/layout.jsx";
import MenuTree from "../components/menuTree/menuTree";
import Article from "../components/artical/article";

export async function getServerSideProps() {
  const { data } = await client.query(
    {
      query: GET_HOME_PAGE,
    },
    {
      variables: {
        getHomePageArticleInput2: {
          nLimit: 10,
          nSkip: 0,
        },
      },
    }
  );
  return {
    props: {
      article: data.getHomePageArticle.aResults,
      totalRecord: data.getHomePageArticle.nTotal,
    },
  };
}

export default function Home({ article }) {
  return (
    <Layout>
      <div>
        <Head>
          <title>Cricktracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
        </Head>
      </div>
      <MenuTree></MenuTree>
      <main className="bg-gray-100">
        <div className="container  mx-auto">
          <div className=" pt-2">
            <div className="grid  gap-4 items-center justify-center pt-4">
              <div className="col-span-2  "></div>
              <div className="col-span-8 ">
                <Article article={article}></Article>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
